bookstore/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("store.urls")),
    path("admin/", admin.site.urls),
]

store/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r"books", views.BookViewSet, basename="book")

app_name = "store"
urlpatterns = [
    path("", RedirectView.as_view(pattern_name="store:book-list"), name="home"),
    path("cart/add", views.add_to_cart, name="cart-add"),
    path("cart/delete", views.delete_from_cart, name="cart-delete"),
    path("cart/update", views.update_cart, name="cart-update"),
    path("cart/", views.show_cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("", include(router.urls)),
]

store/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    key = models.CharField(max_length=10, primary_key=True)
    name = models.TextField()

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"{reverse('store:book-list')}?author={self.pk}"


class Book(models.Model):
    key = models.CharField(max_length=11, primary_key=True)
    title = models.TextField()
    authors = models.ManyToManyField(Author)
    publisher = models.TextField()
    publish_date = models.CharField(max_length=50)
    description = models.TextField()
    cover = models.URLField()
    isbn_10 = models.CharField(max_length=10)
    isbn_13 = models.CharField(max_length=13)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return f"{self.title} by {self._authors()}"

    def _authors(self):
        return ", ".join(author.name for author in self.authors.all())

    def get_absolute_url(self):
        return reverse("store:book-detail", args=[self.pk])

store/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from rest_framework import filters, viewsets
from store.models import Author, Book
from store.serializers import BookSerializer

class BookViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = BookSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ["title", "authors__name"]

    def get_queryset(self):
        queryset = Book.objects.all()
        author_id = self.request.query_params.get("author", None)
        if author_id:
            queryset = queryset.filter(authors__key__contains=author_id)
        return queryset

    def list(self, request, *args, **kwargs):
        self.request.session["bookmark"] = self.request.get_full_path()
        response = super().list(self, request, *args, **kwargs)
        author_id = self.request.query_params.get("author", None)
        if author_id:
            response.data["author"] = Author.objects.get(pk=author_id).name
        search_keyword = self.request.query_params.get("search", None)
        if search_keyword:
            response.data["keyword"] = search_keyword
        return response

    def get_template_names(self):
        if self.action == "list":
            return ["store/index.html"]
        if self.action == "retrieve":
            return ["store/book_details.html"]

@require_POST
def delete_from_cart(request):
    cart = request.session.get("cart", {})
    cart.pop(request.POST["book_id"])
    request.session["cart"] = cart
    if "application/json" in get_acceptable_media_types(request):
        return JsonResponse({"message": "book deleted from cart"}, status=200)
    else:
        return redirect("store:cart")

@require_POST
def update_cart(request):
    cart = request.session.get("cart", {})
    qtys = dict((k, v) for k, v in request.POST.items() if k.startswith("qty"))
    for i, q in qtys.items():
        cart[i[4:]] = int(q)

    request.session["cart"] = cart
    if "application/json" in get_acceptable_media_types(request):
        return JsonResponse({"message": "cart updated"}, status=200)
    else:
        return redirect("store:cart")

@require_POST
def add_to_cart(request):
    book = get_object_or_404(Book, pk=request.POST["book_id"])
    cart = request.session.get("cart", {})
    cart[book.pk] = 1
    request.session["cart"] = cart
    if "application/json" in get_acceptable_media_types(request):
        return JsonResponse({"message": "book added to cart"}, status=201)
    else:
        return redirect(request.META.get("HTTP_REFERER"))

def show_cart(request):
    cart = request.session.get("cart", {})
    response = {"cart": [dict(qty=cart[book.pk],
                              total=cart[book.pk] * book.price,
                              **BookSerializer(book).data)
                         for book in Book.objects.filter(key__in=cart.keys())]}
    response["total_price"] = sum(book["total"] for book in response["cart"])
    if "application/json" in get_acceptable_media_types(request):
        return JsonResponse(response)
    else:
        return render(request, "store/cart.html", response)

def get_acceptable_media_types(request):
    return request.META.get("HTTP_ACCEPT", "*/*").split(",")

def checkout(request):
    return render(request, "store/checkout.html")

store/templates/store/authorslinks.html
{% for author in authors %}
    {% if not forloop.first %}
        {% if forloop.last %}
            and
        {% else %}
            ,
        {% endif %}
    {% endif %}
    <a class="text-body text-decoration-none"
       href="{% url 'store:book-list' %}?author={{ author.key }}"
       title="Show more books by {{ author.name }}">
        {{ author.name }}
    </a>
{% endfor %}

store/templates/store/backlink.html
{% load aux %}
{% if "search" in referer %}
    <a id="id-backlink" class="link-secondary text-decoration-none" href="{{ referer }}">
        ‹ Back to search results for "{{ referer|extract_keywords }}"
    </a>
{% elif "author" in referer %}
    <a id="id-backlink" class="link-secondary text-decoration-none" href="{{ referer }}">
        ‹ Back
    </a>
{% elif "page" in referer %}
    <a id="id-backlink" class="link-secondary text-decoration-none" href="{{ referer }}">
        ‹ Back to catalog
    </a>
{% else %}
    <a id="id-backlink" class="link-secondary text-decoration-none" href="{% url 'store:home' %}">
        ‹ Back to catalog
    </a>
{% endif %}

store/templates/store/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet"
              href="{% static 'bootstrap/css/bootstrap.min.css' %}"
              integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" />
        <link rel="stylesheet" type="text/css" href="{% static 'store/style.css' %}" />
        <link rel="shortcut icon" type="image/png"
              href="{% static 'store/favicon.ico' %}" />
        <title>{% block title_text %}{% endblock %}</title>
    </head>
    <body>
        <noscript>
            <div class="vh-100 d-flex flex-column">
                <div class="container content">
                    {% block header %}
                    <header class="row align-items-center">
                        <a class="col-auto text-body text-decoration-none" href="{% url 'store:home' %}">
                            <h1>Bookstore</h1>
                        </a>
                        <form class="col input-group search-bar" action="{% url 'store:book-list' %}">
                            <input name="search" type="text" class="form-control" aria-label="Search catalog">
                            <button class="btn search-btn input-group-text" type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                                </svg>
                            </button>
                        </form>
                        <div class="col-auto">
                            <a id="id-cart" title="Shopping Cart" class="text-uppercase fw-bold btn btn-outline-secondary"
                                                                  href="{% url 'store:cart' %}">
                                🛒 Cart
                                {% if request.session.cart|length %}
                                [{{ request.session.cart|length }}]
                                {% endif %}
                            </a>
                        </div>
                    </header>
                    {% endblock %}
                    <div class="row">
                        {% block body %}{% endblock %}
                    </div>
                </div>
                {% block footer %}
                <footer class="row py-3">
                    <div class="col text-center">
                        All books data is borrowed from&nbsp;
                        <a href="https://openlibrary.org/">Open Library</a>;&nbsp;
                        prices are generated randomly
                    </div>
                </footer>
                {% endblock %}
            </div>
        </noscript>
        <script src="{% static 'react/react.production.min.js' %}"></script>
        <script src="{% static 'react/react-dom.production.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/index.js' %}"></script>
    </body>
</html>

store/templates/store/book_details.html
{% extends "store/base.html" %}
{% block title_text %}{{ title|title }} by {{ authors|names }}{% endblock %}
{% block body %}
    <div class="row">
        {% include "store/backlink.html" with referer=request.session.bookmark %}
    </div>
    <div id="id-book-details" class="info-window rounded">
        <div class="row my-2">
            <div class="col-auto my-2">
                <img src="{{ cover }}"
                     class="rounded"
                     alt="{{ title|title }} by {{ authors|names }}" />
            </div>
            <div class="col">
                <h1>{{ title|title }}</h1>
                <h2>{% include "store/authorslinks.html" with authors=authors %}</h2>
                <h4 class="py-3">{{ description }}</h4>
                <p><b>Publisher:</b> {{ publisher }}</p>
                <p><b>Publication date:</b> {{ publish_date }}</p>
                <p><b>ISBN-10:</b> {{ isbn_10 }}</p>
                <p><b>ISBN-13:</b> {{ isbn_13 }}</p>
            </div>
            <div class="col-auto d-flex flex-column text-end">
                <h2 class="my-2">${{ price }}</h2>
                <div class="mt-auto my-3">
                    {% if key in request.session.cart %}
                        <form action="{% url 'store:cart' %}">
                            <button class="text-uppercase fw-bold btn btn-secondary">
                                in cart
                            </button>
                        </form>
                    {% else %}
                        <form action="{% url 'store:cart-add' %}" method="POST">
                            {% csrf_token %}
                            <button class="text-uppercase fw-bold btn btn-outline-secondary"
                                    name="book_id"
                                    value="{{ key }}">
                                add to cart
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

store/templates/store/cart.html
{% extends "store/base.html" %}
{% block title_text %}Your Shopping Cart{% endblock %}
{% block header %}{% endblock %}
{% block body %}
    {% if cart %}
        <div class="row">
            <h1 class="col">Your Shopping Cart</h1>
        </div>
        <div class="row">
            {% include "store/backlink.html" with referer=request.session.bookmark %}
        </div>
        <form id="id-update-form" action="{% url 'store:cart-update' %}" method="POST">
            {% csrf_token %}
        </form>
        <div class="row">
            <table id="id-book-catalog" class="table table-borderless table-striped">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>Title</th>
                        <th>Authors</th>
                        <th>Price</th>
                        <th>Qty</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                        <tr class="align-middle">
                            <td>{{ forloop.counter }}.</td>
                            <td>
                                <a class="text-body" href="{% url 'store:book-detail' item.key %}">
                                    {{ item.title|title }}
                                </a>
                            </td>
                            <td>{% include "store/authorslinks.html" with authors=item.authors %}</td>
                            <td>${{ item.price }}</td>
                            <td>
                                <input type="number"
                                       min="1"
                                       size="4"
                                       name="qty {{ item.key }}"
                                       value="{{ item.qty }}"
                                       form="id-update-form">
                            </td>
                            <td>${{ item.total }}</td>
                            <td>
                                <form action="{% url 'store:cart-delete' %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn-close" aria-label="Delete"
                                            name="book_id"
                                            value="{{ item.key }}">
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Subtotal</th>
                    <th id="id-total-price">${{ total_price }}</th>
                    <th></th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="row">
            <div class="col">
            </div>
            <div class="col-auto">
                <button name="update" class="btn btn-primary" form="id-update-form">
                    update cart
                </button>
                <a id="id-checkout-button" class="btn btn-primary" href="{% url 'store:checkout' %}">
                    checkout
                </a>
            </div>
        </div>
    {% else %}
        <div class="row vh-100 align-items-center text-center">
            <div>
                <h3 class="my-3">Your Shopping Cart is empty</h3>
                {% include "store/backlink.html" with referer=request.session.bookmark %}
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block footer %}{% endblock %}

store/templates/store/checkout.html
{% extends "store/base.html" %}
{% block title_text %}Checkout{% endblock %}
{% block header %}{% endblock %}
{% block body %}
    <div id="checkout" class="row vh-100 align-items-center text-center">
        <div>
            <h1 class="my-3">This is a demo store. You can't buy a real thing here.</h1>
            {% include "store/backlink.html" with referer=request.session.bookmark %}
        </div>
    </div>
{% endblock %}
{% block footer %}{% endblock %}

store/templates/store/index.html
{% extends "store/base.html" %}
{% block title_text %}Bookstore{% endblock %}
{% block body %}
    {% if keyword %}
        <h5>Search results for "{{ keyword }}":</h5>
    {% elif author %}
        <h5>Books by {{ author }}:</h5>
    {% endif %}
    {% if results %}
        <div id="id-book-catalog" class="row justify-content-center info-window rounded">
            {% for book in results %}
                <div class="card text-end mx-2 my-2 px-0 py-0">
                    <a href="{% url 'store:book-detail' book.key %}">
                        <img src="{{ book.cover }}"
                             class="card-img-top"
                             alt="{{ book.title|title }} by {{ book.authors|names }}"
                             title="{{ book.title|title }} by {{ book.authors|names }}" />
                    </a>
                    <div class="card-body d-flex flex-column">
                        <p class="card-text fw-bold">${{ book.price }}</p>
                        {% if book.key in request.session.cart %}
                            <form action="{% url 'store:cart' %}">
                                <button class="text-uppercase fw-bold btn btn-secondary">
                                    in cart
                                </button>
                            </form>
                        {% else %}
                            <form action="{% url 'store:cart-add' %}" method="POST">
                                {% csrf_token %}
                                <button class="text-uppercase fw-bold btn btn-outline-secondary"
                                        name="book_id"
                                        value="{{ book.key }}">
                                    add to cart
                                </button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No books are available.</p>
    {% endif %}
{% endblock %}
{% block footer %}
<footer class="row py-3">
    <nav class="row mx-2 my-2" aria-label="book catalog pages">
        <ul class="pagination justify-content-center">
            {% for page_link in page_links %}
                {% if page_link.is_break %}
                    <li class="page-item">
                        <a class="page-link disabled" href="#">
                            <span aria-hidden="true">&hellip;</span>
                        </a>
                    </li>
                {% else %}
                    {% if page_link.is_active %}
                        <li class="page-item active">
                            <a class="page-link"
                               href="{{ page_link.url }}"
                               aria-label="{{ page_link.number }}">
                                {{ page_link.number }}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ page_link.url }}"
                               aria-label="{{ page_link.number }}">
                                {{ page_link.number }}
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
    <div class="col text-center">
        All books data is borrowed from&nbsp;
        <a href="https://openlibrary.org/">Open Library</a>;&nbsp;
        prices are generated randomly
    </div>
</footer>
{% endblock %}